# Review session

General reminder: use `dir()` and `help()` to find methods and their help 

## 1. Lists, indexing, list comprehension

* a list is a container which can be indexed by an integer
* all elements in a list do not have to be of the same type
* indices start from 0
* syntax: `[1, 2, 'a', [1,2,3]]`
* initialize an empty list: `l = []`
* addition is concatenation (also `append` method)
* list comprehension: a concise way to create a list: `newlist = [expression for item in iterable if condition == True]`
* iterating over all items in a list:
   * `for it in l:`
   * if position is required: `for idx, it in enumerate(l):`
   * 
* nested list (lists of lists), indexing...


In [3]:
l = [1,2,3]
print(l[0], l[1], l[2])

1 2 3


In [ ]:
# a list consisting or all even numbers  less than 21 that are not multiples of 3:
l = [i for i in range(22) if i%2 == 0 and i%3 != 0]
print(l)



[2, 4, 8, 10, 14, 16, 20]


In [14]:
# list comprehension can be quite complex
l = [ i if i%3!=0 else '_' for i in range(22) if i%2 == 0]
print(l)


['_', 2, 4, '_', 8, 10, '_', 14, 16, '_', 20]


## 2. Dictionaries
* think of them as list whose indices can be anything, or as collections of `key:value` pairs
* a convenient way to organize structured data
* most common use is with keys being string 
* syntax: `D = {key1:value1, key2:values2, }`, `student = {'first name': 'john', 'last name': 'Doe', 'ID':400123456}`
* special methods: `D.keys()`, `D.values()`, `D.update()`

In [27]:
student = {'first name': 'john', 'last name': 'Doe', 'ID':400123456}

In [25]:
print(student.keys())
print(student.values())
student.update({'grades':[1,2,3,4]})
print(student)

dict_keys(['first name', 'last name'])
dict_values(['john', 'Doe'])
{'first name': 'john', 'last name': 'Doe', 'grades': [1, 2, 3, 4]}


In [26]:
student.update({'attendance': [True, False, True, False], 'grades':[1,2,3,4,5]})
print(student)

{'first name': 'john', 'last name': 'Doe', 'grades': [1, 2, 3, 4, 5], 'attendance': [True, False, True, False]}


In [ ]:
# loop over all pairs in a dict
for k in student.keys():
    print(f"{k}: {student[k]}")

first name: john
last name: Doe
ID: 400123456
first name: john
last name: Doe
ID: 400123456


In [ ]:
# equivalent:
for k in student:
    print(f"{k}: {student[k]}")

first name: john
last name: Doe
ID: 400123456


## 3. Functions, scope, side effects
* functions promote code reuse.
* syntax: 
    ```
    def f(parameter1, parameter2):
    """ doc string used for help"""
        # some work
        return val1, val2
    ```
* scope:
    * variables created inside a function (*local* variables) are only visible inside the function.
    * variable created outside (*global* variables) the function are visible but cannot be modified.
    * creating a *local* variable with the same name as a *global* variable is possible, but a variable cannot be both local and global.
* side effects: when a function affects variables outside its scope (careful with containers). A general rule to avoid side effects: think carefully before doing assignments with containers. 

In [41]:
x = 3
def f(y):
    return x+y
print(f(1))

4


In [43]:
def g(y):
    y = x
    return x+y
y = 2
print(g(y))
print(y)

6
2


In [ ]:
# a function with easily tracked side effects
l1 = [1,2,3,4]
def SE1(l):
    l[0] = 'Hello!'
    return len(l)
print(l1)
print(SE1(l1))
print(l1)

[1, 2, 3, 4]
4
['Hello!', 2, 3, 4]


In [ ]:
# more subtle side effects
l1 = [1,2,3,4]
l2 = [4,5,6,7]
def SE2(l):
    l = l2
    l[0] = 'Hello!'
    return len(l)
print(l1, l2)
print(SE2(l1))
print(l1, l2)

[1, 2, 3, 4] [4, 5, 6, 7]
4
[1, 2, 3, 4] ['Hello!', 5, 6, 7]


## 4. `numpy`, `ndarray`s, `Polynomials`
* `numpy` is a collection of tools for numerical computations. Traditionally imported as `import numpy as np`
* `ndarray`s
    * think of `ndarrays` as vectorized lists (*i.e.* list for which most operations are applied item-wise)
    * basic syntax: `u = np.array([1,2,3])`, `v = np.array([[1,2,3],[4,5,6]])`
    * `ndim` = dimensionality of the aray (number of axes)
    * `shape` = size along each axes
    * `size` = total number of values (= product of shape)
    * indexing as nested lists, or directly by multi-index
    * usual commands for sections work


In [51]:
import numpy as np
v = np.array([[1,2,3],[4,5,6]])
print(v.ndim)
print(v.shape)
print(v.size)

2
(2, 3)
6


In [55]:
# indexing as nexted list
print(v[0][1])
# indexing with multi-indices
print(v[0,1])


# first row of v as nested list
print(v[0])
# first row of v with multi-indices
print(v[0,:])

2
2
[1 2 3]
[1 2 3]


In [ ]:
# first column as nested list
print(np.array([r[0] for r in v]))

# first column using multi-indices much easier
print(v[:,0])


[1 4]
[1 4]


In [ ]:
# indexing of 3d arrays: right hand rule, first axis pointing towards you, second axis pointing down, third axis pointing down
# last index mo
L = np.array([[[1, 2, 3], 
               [10, 20, 30]],
              [[4, 5, 6],
               [40, 50, 60]]])

       1----2----3
      /    /    /|
     /    /    / |
    4----5----6  |
    |    |    |  30
    |    |    | / 
    |    |    |/ 
    40---50---60

In [67]:
print(L[0,:,:])
print(L[:,0,:])
print(L[:,:,0])

[[ 1  2  3]
 [10 20 30]]
[[1 2 3]
 [4 5 6]]
[[ 1 10]
 [ 4 40]]


In [ ]:
print(L[ 0, 0, 0])
print(L[-1, 0, 0])
print(L[ 0,-1, 0])
print(L[ 0, 0,-1])

1
4
10
3
