# Chapter 14. `numpy`

`numpy` provides many low level tools for computational work with python.
The most important ones are `ndarrays`, *i.e.* n-dimensional arrays.

## 14.1: `ndarray`

Python lists are not the same as math vectors. In particular, the addition, scalar multiplication etc of lists does not work the way math vectors work.

Let's start with one-dimensional arrays and compare the following


In [5]:
A = [1, 2, 3]
B = [2, 7, 9]
print(A + B)
print(2*A)
print(A*2)


[1, 2, 3, 2, 7, 9]
[1, 2, 3, 1, 2, 3]
[1, 2, 3, 1, 2, 3]


In [4]:
print(A*2.5)

TypeError: can't multiply sequence by non-int of type 'float'

In [3]:
import numpy as np
A = np.array([1, 2, 3]) # A, B are ndarrays
B = np.array([2, 7, 9])
# print(A + B)

print(A * B)



[ 2 14 27]


Short version: most algebraic operators apply on each term (dot operators with matlab). Python calls this "broadcasting".


In [7]:
def f(x):
    return x**2+1
print(f(B))
print(2*B)
print(B*2)
print(B+1)


[ 5 50 82]
[ 4 14 18]
[ 4 14 18]
[ 3  8 10]


We'll see later more ways to initialize ndarrays, but for instance, 
```
M = np.array([[1,2,3], [4,5,6], [7,8,9]])
``` 
will initialize a two-dimensional ndarray

In [4]:
M = np.array([[1,2,3], [4,5,6], [7,8,9]])
print(M)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


Unlike python arrays, all elements of a ndarray must be of the same type, all rows (sections) of a ndarray must be of the same size, and the size cannot be changed

In [17]:

u = np.array([1,2,3])
# u.append(2)
print(u)
# 

print(u)

A = [[1,2,3], [4,5]]
print(A)



[1 2 3]
[1 2 3]
[[1, 2, 3], [4, 5]]


In [6]:
u = np.array([[1,2, 3], [3,4]])

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.

## 14.2 Axes
In order to avoid confusion between the shape of `ndarray`s and the data they represent, numpy refers do dimension as `axes`.

For instance, `np.array([[1,2,3],[4,5,6])` could represent 2 points in 3 dimensional space, or 3 points in the plane, but numpy think of oit as an array with 2 axes.

Element of arrays with more than 1 axis can be indexed by specifiying all indices in a single set of square brackets

In [7]:
A = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print("A: ",A)
print("A[0]: ", A[0])
print("A[0,0]: ", A[0,0]) # same as A[0][0] but more compact

A:  [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
A[0]:  [1 2 3 4]
A[0,0]:  1


Basic information on axes:
* `ndim`: number of axes
* `shape`: length along all axes
* `size`: total number of values

In [8]:
print(A)
print("A.ndim:  ", A.ndim)
print("A.shape: ", A.shape)
print("A.size:  ", A.size)


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
A.ndim:   2
A.shape:  (3, 4)
A.size:   12


In [18]:
l =  [[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]
len(l)


3

In [24]:
B = np.array([[[0, 1, 2, 3],
               [4, 5, 6, 7]],
              [[10, 11, 12, 13],
               [14, 15, 16, 17]],
              [[20 ,21 ,22, 23],
               [24, 25, 26, 27]]])
print(B)
print("B.ndim:  ", B.ndim)
print("B.shape: ", B.shape)
print("B.size:  ", B.size)



[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[10 11 12 13]
  [14 15 16 17]]

 [[20 21 22 23]
  [24 25 26 27]]]
B.ndim:   3
B.shape:  (3, 2, 4)
B.size:   24


In [32]:
print(B[2,1,2])

print(B[0,1,2:4])


print(B[:,:,0])
print(B[0:2,0:2,1])


26
[6 7]
[[ 0  4]
 [10 14]
 [20 24]]
[[ 1  5]
 [11 15]]


For most operations, one can specify an axis along which to operate, for instance:

In [39]:
A = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(A)

print(A.sum())

print(A.sum(axis=0))
print(A.sum(axis=1))



[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
78
[15 18 21 24]
[10 26 42]


## 14.3 Commonly used arrays
* `zeros`: arrays full of 0s
*  `ones`: array full of 1s
*  `empty`: empty array (useful since ndarrays cannot be extended)
*  `arange`: arrays with a range of numbers. Unlike `range`, elements do not have to be integers
*  `linspace`: arrays with equally spaced elements
*  `eye`: 2D identity matrix
*  `meshgrid`: create a set of (x,y) coordinates given x and y

In [9]:
#print(np.empty( (4,3) ))
import numpy as np

for i in range(3):
    print(i)
    
for i in [0,1,2]:
    print(i)
print(range(3))

# n -> 0, 1, 2, 3, 4, 5 ... n-1]
n = 5


l = []
i = 0
while i < n:
    l.append(i)
    i += 1
print(l)

l = [i for i in range(n)]
print(l)

L = np.arange(1,5,2)

print(L)
print(np.linspace(0,1,5))




#print(np.arange(1.5, 9.5, 2))
#print(np.linspace(0,1,8))

0
1
2
0
1
2
range(0, 3)
[0, 1, 2, 3, 4]
[0, 1, 2, 3, 4]
[1 3]
[0.   0.25 0.5  0.75 1.  ]


In [12]:
print(np.zeros( (2,3) ))
print(np.empty( (3,3) )) # values are uninitialized and can be anything

[[0. 0. 0.]
 [0. 0. 0.]]
[[ 1.14285714 -2.28571429  0.57142857]
 [-2.28571429  4.97142857 -1.54285714]
 [ 0.57142857 -1.54285714  0.88571429]]


In [15]:
x = np.linspace(0,1,4)
y = np.linspace(2,3,5)
print(x)
print(y)


[0.         0.33333333 0.66666667 1.        ]
[2.   2.25 2.5  2.75 3.  ]


tuple

## 14.4 Indexing
Usual indexing rules apply and can be used along any axis

In [13]:
A = np.array([1,2,3,4,5,6])
print(A[:2], A[2:])
print(A[2:4])
print(A[0::2])


[1 2] [3 4 5 6]
[3 4]
[1 3 5]


In [14]:
A = np.array([[[0, 1, 2, 3],
               [4, 5, 6, 7]],
              [[10, 11, 12, 13],
               [14, 15, 16, 17]],
              [[20 ,21 ,22, 23],
               [24, 25, 26, 27]]])
print(A[0,:,:])
print(A[:,0,:])
print(A[:,:,0])

[[0 1 2 3]
 [4 5 6 7]]
[[ 0  1  2  3]
 [10 11 12 13]
 [20 21 22 23]]
[[ 0  4]
 [10 14]
 [20 24]]


## 14.5 masking / filtering

In [17]:
a = np.arange(12)
print(a)

print(a>4)

print(a[a>4])


[ 0  1  2  3  4  5  6  7  8  9 10 11]
[False False False False False  True  True  True  True  True  True  True]
[ 5  6  7  8  9 10 11]


In [19]:
A = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

print(A)

print(A%2==0)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[False  True False  True]
 [False  True False  True]
 [False  True False  True]]


In [20]:
print(A * (A%2 == 0))


[[ 0  2  0  4]
 [ 0  6  0  8]
 [ 0 10  0 12]]


## 14.6 stacking
* `hstack`
* `vstack`
* `dstack`


In [18]:
a1 = np.array([[1, 1],
               [2, 2]])

a2 = np.array([[3, 3],
               [4, 4]])

In [19]:
np.vstack((a1, a2))

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

In [20]:
np.hstack((a1, a2))

array([[1, 1, 3, 3],
       [2, 2, 4, 4]])

In [21]:
A = np.array([[[0, 1, 2, 3],
               [4, 5, 6, 7]],
              [[10, 11, 12, 13],
               [14, 15, 16, 17]],
              [[20 ,21 ,22, 23],
               [24, 25, 26, 27]]])
np.dstack((A,A))

array([[[ 0,  1,  2,  3,  0,  1,  2,  3],
        [ 4,  5,  6,  7,  4,  5,  6,  7]],

       [[10, 11, 12, 13, 10, 11, 12, 13],
        [14, 15, 16, 17, 14, 15, 16, 17]],

       [[20, 21, 22, 23, 20, 21, 22, 23],
        [24, 25, 26, 27, 24, 25, 26, 27]]])

## 14.7 reshaping
numpy arrays can be reshaped (provided that it does not change the size). Note that reshaping does not change the underlying data (i.e., does not reorder terms)

In [33]:
a = np.arange(24)
# print(a.reshape(4,6))
# print(a.reshape(6,4))
print(a.reshape((2,3,4)))

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


## 14.8 loading and saving data with numpy

In [22]:
a = np.array([[-2.58289208,  0.43014843, -1.24082018, 1.59572603],
              [ 0.99027828, 1.17150989,  0.94125714, -0.14692469],
              [ 0.76989341,  0.81299683, -0.95068423, 0.11769564],
              [ 0.20484034,  0.34784527,  1.96979195, 0.51992837]])

In [23]:
np.savetxt('example2.csv', a, delimiter = ', ')

In [35]:
b = np.loadtxt('example2.csv', delimiter = ',')

In [36]:
print(b)

[[-2.58289208  0.43014843 -1.24082018  1.59572603]
 [ 0.99027828  1.17150989  0.94125714 -0.14692469]
 [ 0.76989341  0.81299683 -0.95068423  0.11769564]
 [ 0.20484034  0.34784527  1.96979195  0.51992837]]


## 14.9 linear algebra

M = np.array([1,2,3,4]).reshape(2,2)

In [43]:
M * M

array([[ 1,  4],
       [ 9, 16]])

## 14.9 linear algebra
Warning: `*` does term by term product. Matrix product is `@`, vector dot product is `vdot` or `vecdot`

In [46]:
M = np.array([1,2,3,4]).reshape((2,2))

In [48]:
M*M

array([[ 1,  4],
       [ 9, 16]])

In [49]:
M@M

array([[ 7, 10],
       [15, 22]])

In [59]:
u = np.array([3,4,5])
v = np.array([1,2,3])
print(np.vdot(u,v))
print(np.linalg.cross(u,v))

26
[ 2 -4  2]
