# Review session

General reminder: use `dir()` and `help()` to find methods and their help 

## 1. Lists, indexing, list comprehension

* a list is a container which can be indexed by an integer
* all elements in a list do not have to be of the same type
* indices start from 0
* syntax: `[1, 2, 'a', [1,2,3]]`
* initialize an empty list: `l = []`
* addition is concatenation (also `append` method)
* list comprehension: a concise way to create a list: `newlist = [expression for item in iterable if condition == True]`
* iterating over all items in a list:
   * `for it in l:`
   * if position is required: `for idx, it in enumerate(l):`
   * 
* nested list (lists of lists), indexing...


In [2]:
l = [1,2,3]
print(l[0], l[1], l[2])
l = [0] + l
print(l)
#l = l + [4]
l.append(4)
print(l)


1 2 3
[0, 1, 2, 3]
[0, 1, 2, 3, 4]


In [8]:
# duplicate l:
l2 = [i for i in l]
print(l2)
l3 = [i for i in l if i%2 != 0]
print(l3)




[0, 1, 2, 3, 4]
[1, 3]


In [18]:
# create
# [[0],
#  [0,1],
#  [0,1,2],
#  :
#  [0,1,2,3 ... n]]
# given n

# step 1: row j:
j = 3
row = [i for i in range(j)]
print(row)

n = 5
triangleList = [ [i for i in range(j+1)] for j in range(n)]
print(triangleList)

triangleList = [ [i for i in range(j)] for j in range(1,n+1)]

print(triangleList)

#sequence:
L = [2*n**2+1 for n in range(10)]
print(L)




[0, 1, 2]
[[0], [0, 1], [0, 1, 2], [0, 1, 2, 3], [0, 1, 2, 3, 4]]
[[0], [0, 1], [0, 1, 2], [0, 1, 2, 3], [0, 1, 2, 3, 4]]
[1, 3, 9, 19, 33, 51, 73, 99, 129, 163]


In [ ]:
# a list consisting or all even numbers less than 21 that are not multiples of 3:
l = [i for i in range(22) if i%2 == 0 and i%3 != 0]
print(l)



[2, 4, 8, 10, 14, 16, 20]


In [21]:
# list comprehension can be quite complex
# l = [ i if i%3!=0 else '*' for i in range(22) if i%2 == 0]
l = [ i if i%3!=0 else '*' for i in range(22) if i%2 == 0]
print(l)

['*', 2, 4, '*', 8, 10, '*', 14, 16, '*', 20]


## 2. Dictionaries
* think of them as list whose indices can be anything, or as collections of `key:value` pairs
* a convenient way to organize structured data
* most common use is with keys being string 
* syntax: `D = {key1:value1, key2:values2, }`, `student = {'first name': 'john', 'last name': 'Doe', 'ID':400123456}`
* special methods: `D.keys()`, `D.values()`, `D.update()`

In [22]:
student = {'first name': 'john', 'last name': 'Doe', 'ID': 400123456}

In [26]:
student = {'first name': 'john', 'last name': 'Doe', 'ID': 400123456}
print(student.keys())
print(student.values())
student['email'] = 'johndoe@mcmaster.ca'
print(student)
student.update({'grades':[1,2,3,4]})
print(student)



dict_keys(['first name', 'last name', 'ID'])
dict_values(['john', 'Doe', 400123456])
{'first name': 'john', 'last name': 'Doe', 'ID': 400123456, 'email': 'johndoe@mcmaster.ca'}
{'first name': 'john', 'last name': 'Doe', 'ID': 400123456, 'email': 'johndoe@mcmaster.ca', 'grades': [1, 2, 3, 4]}


In [27]:
student.update({'attendance': [True, False, True, False], 'grades':[1,2,3,4,5]})
print(student)


{'first name': 'john', 'last name': 'Doe', 'ID': 400123456, 'email': 'johndoe@mcmaster.ca', 'grades': [1, 2, 3, 4, 5], 'attendance': [True, False, True, False]}


In [28]:
# loop over all pairs in a dict
for k in student.keys():
    print(f"{k}: {student[k]}")
    

first name: john
last name: Doe
ID: 400123456
email: johndoe@mcmaster.ca
grades: [1, 2, 3, 4, 5]
attendance: [True, False, True, False]


In [29]:
# equivalent:
for k in student:
    print(f"{k}: {student[k]}")
    

first name: john
last name: Doe
ID: 400123456
email: johndoe@mcmaster.ca
grades: [1, 2, 3, 4, 5]
attendance: [True, False, True, False]


## 3. Functions, scope, side effects
* functions promote code reuse.
* syntax: 
    ```
    def f(parameter1, parameter2):
    """ doc string used for help"""
        # some work
        return val1, val2
    ```
* scope:
    * variables created inside a function (*local* variables) are only visible inside the function.
    * variable created outside (*global* variables) the function are visible but cannot be modified.
    * creating a *local* variable with the same name as a *global* variable is possible, but a variable cannot be both local and global.
* side effects: when a function affects variables outside its scope (careful with containers). A general rule to avoid side effects: think carefully before doing assignments with containers. 

In [33]:
def scope1(x):
    y = 2*x
    print('inside scope1:', y)
    return y
print(scope1(2))
print(y)



inside scope1: 4
4


NameError: name 'y' is not defined

In [35]:
x = 3
def f(y):
    return x+y
print(f(1))

def f2(y):
    x = 4
    return x+y
print(f2(1))
print(x)


4
5
3


In [41]:
x = 3

def f3(y): 
    y += x # suggests that either x is a global variable or a newly create local variable
    x = 1  # suggests that x is a local variable 
    y -= x
    return y

y = 1
print(x,f3(y),x,y)





3 1 3 1


In [44]:
def g(y):
    y = x
    return x+y
y = 2
print(g(y))
print(y)



6
2


In [45]:
# a function with easily tracked side effects
l1 = [1,2,3,4]
def SE1(l):
    l[0] = 'Hello!'
    return len(l)
print(l1)
print(SE1(l1))
print(l1)



[1, 2, 3, 4]
4
['Hello!', 2, 3, 4]


In [47]:
l1 = [1,2,3,4]
def SE10(l):
    # l.append('Hello!')
    l = ['a', 'b', 'c', 'd']
    return len(l)
print(l1)
print(SE10(l1))
print(l1)


[1, 2, 3, 4]
4
[1, 2, 3, 4]


In [ ]:
# more subtle side effects
l1 = [1,2,3,4]
l2 = [4,5,6,7]
def SE2(l):
    l = l2
    l[0] = 'Hello!'
    return len(l)
print(l1, l2)
print(SE2(l1))
print(l1, l2)

[1, 2, 3, 4] [4, 5, 6, 7]
4
[1, 2, 3, 4] ['Hello!', 5, 6, 7]


In [52]:
def add(l1, l2):
    sum = l1
    for i in range(2):
        sum[i] = sum[i] + l2[i]
    return sum        
s1 = [1,2]
s2 = [10, 20]
s3 = add(s1, s2)
print(s3)
print(s1)



        

[11, 22]
[11, 22]


## 4. `numpy`, `ndarray`s, `Polynomials`
* `numpy` is a collection of tools for numerical computations. Traditionally imported as `import numpy as np`
* `ndarray`s
    * think of `ndarrays` as vectorized lists (*i.e.* list for which most operations are applied item-wise)
    * basic syntax: `u = np.array([1,2,3])`, `v = np.array([[1,2,3],[4,5,6]])`
    * `ndim` = dimensionality of the aray (number of axes)
    * `shape` = size along each axes
    * `size` = total number of values (= product of shape)
    * indexing as nested lists, or directly by multi-index
    * usual commands for sections work


In [1]:
import numpy as np
v = np.array([[1,2,3],[4,5,6]])
print(v.ndim)
print(v.shape)
print(v.size)


2
(2, 3)
6


In [55]:
# indexing as nexted list
print(v[0][1])
# indexing with multi-indices
print(v[0,1])


# first row of v as nested list
print(v[0])
# first row of v with multi-indices
print(v[0,:])

2
2
[1 2 3]
[1 2 3]


In [ ]:
# first column as nested list
print(np.array([r[0] for r in v]))

# first column using multi-indices much easier
print(v[:,0])


[1 4]
[1 4]


In [2]:
# indexing of 3d arrays: right hand rule, first axis pointing towards you, second axis pointing down, third axis pointing down
# last index mo
L = np.array([[[1, 2, 3], 
               [10, 20, 30]],
              [[4, 5, 6],
               [40, 50, 60]]])
print(L.ndim)
print(L.shape)
print(L.size)


3
(2, 2, 3)
12


       1----2----3
      /    /    /|
     /    /    / |
    4----5----6  |
    |    |    |  30
    |    |    | / 
    |    |    |/ 
    40---50---60

In [6]:
print(L[1,:,:])
print(L[:,0,:])
print(L[:,:,2])



[[ 4  5  6]
 [40 50 60]]
[[1 2 3]
 [4 5 6]]
[[ 3 30]
 [ 6 60]]


In [ ]:
print(L[ 0, 0, 0])
print(L[-1, 0, 0])
print(L[ 0,-1, 0])
print(L[ 0, 0,-1])

1
4
10
3
